[package]
name = "terrust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "*"
bevy_egui = "*"
rand = "*"
bevy_flycam = "*"
noise = "0.7"
bevy_atmosphere = "*"
meshx = "*"

[profile.dev]
opt-level = 3

[profile.release]
lto = "thin"
