[package]
name = "cell3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "*"
rand = "*"
bevy_flycam = "*"
noise = "0.7.0"
bevy_atmosphere = "*"

[profile.dev]
opt-level = 0

[profile.release]
lto = "thin"
